"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import { store } from "../../store/createConfigue/Store";
const inter = Inter({ subsets: ["latin"] });

import Nav from "../components/navbar/Nav";
import { MantineProvider } from "@mantine/core";
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Toaster position="bottom-center" reverseOrder={false} />
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
